apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-remote
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nextcloud/helm.git'
    path: charts/nextcloud
    targetRevision: nextcloud-3.3.6
    helm:
      parameters:
        - name: cronjob.enabled
          value: 'true'
      valueFiles: ['values.yaml']
  #    valueFrom:
  #      secretKeyRef:
  #        name: nextcloud
  #        key: secret_key
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextcloud
